// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/replication.proto

package replication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_OP_CREATE_USER  OperationType = 0
	OperationType_OP_CREATE_TOPIC OperationType = 1
	OperationType_OP_POST_MESSAGE OperationType = 2
	OperationType_OP_LIKE_MESSAGE OperationType = 3
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OP_CREATE_USER",
		1: "OP_CREATE_TOPIC",
		2: "OP_POST_MESSAGE",
		3: "OP_LIKE_MESSAGE",
	}
	OperationType_value = map[string]int32{
		"OP_CREATE_USER":  0,
		"OP_CREATE_TOPIC": 1,
		"OP_POST_MESSAGE": 2,
		"OP_LIKE_MESSAGE": 3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_replication_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_replication_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{0}
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // log index (monotonic)
	Type          OperationType          `protobuf:"varint,2,opt,name=type,proto3,enum=replication.OperationType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // serialized request
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Operation) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OP_CREATE_USER
}

func (x *Operation) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Operation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type AckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // confirmed log index
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *AckMessage) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type GetLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIndex     int64                  `protobuf:"varint,1,opt,name=from_index,json=fromIndex,proto3" json:"from_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogRequest) Reset() {
	*x = GetLogRequest{}
	mi := &file_proto_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogRequest) ProtoMessage() {}

func (x *GetLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogRequest.ProtoReflect.Descriptor instead.
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{2}
}

func (x *GetLogRequest) GetFromIndex() int64 {
	if x != nil {
		return x.FromIndex
	}
	return 0
}

var File_proto_replication_proto protoreflect.FileDescriptor

const file_proto_replication_proto_rawDesc = "" +
	"\n" +
	"\x17proto/replication.proto\x12\vreplication\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n" +
	"\tOperation\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.replication.OperationTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\"\n" +
	"\n" +
	"AckMessage\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\".\n" +
	"\rGetLogRequest\x12\x1d\n" +
	"\n" +
	"from_index\x18\x01 \x01(\x03R\tfromIndex*b\n" +
	"\rOperationType\x12\x12\n" +
	"\x0eOP_CREATE_USER\x10\x00\x12\x13\n" +
	"\x0fOP_CREATE_TOPIC\x10\x01\x12\x13\n" +
	"\x0fOP_POST_MESSAGE\x10\x02\x12\x13\n" +
	"\x0fOP_LIKE_MESSAGE\x10\x032\x8f\x01\n" +
	"\vReplication\x12<\n" +
	"\tReplicate\x12\x16.replication.Operation\x1a\x17.replication.AckMessage\x12B\n" +
	"\n" +
	"GetLogFrom\x12\x1a.replication.GetLogRequest\x1a\x16.replication.Operation0\x01B\x0eZ\f/replicationb\x06proto3"

var (
	file_proto_replication_proto_rawDescOnce sync.Once
	file_proto_replication_proto_rawDescData []byte
)

func file_proto_replication_proto_rawDescGZIP() []byte {
	file_proto_replication_proto_rawDescOnce.Do(func() {
		file_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)))
	})
	return file_proto_replication_proto_rawDescData
}

var file_proto_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_replication_proto_goTypes = []any{
	(OperationType)(0),            // 0: replication.OperationType
	(*Operation)(nil),             // 1: replication.Operation
	(*AckMessage)(nil),            // 2: replication.AckMessage
	(*GetLogRequest)(nil),         // 3: replication.GetLogRequest
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_replication_proto_depIdxs = []int32{
	0, // 0: replication.Operation.type:type_name -> replication.OperationType
	4, // 1: replication.Operation.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: replication.Replication.Replicate:input_type -> replication.Operation
	3, // 3: replication.Replication.GetLogFrom:input_type -> replication.GetLogRequest
	2, // 4: replication.Replication.Replicate:output_type -> replication.AckMessage
	1, // 5: replication.Replication.GetLogFrom:output_type -> replication.Operation
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_replication_proto_init() }
func file_proto_replication_proto_init() {
	if File_proto_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_replication_proto_goTypes,
		DependencyIndexes: file_proto_replication_proto_depIdxs,
		EnumInfos:         file_proto_replication_proto_enumTypes,
		MessageInfos:      file_proto_replication_proto_msgTypes,
	}.Build()
	File_proto_replication_proto = out.File
	file_proto_replication_proto_goTypes = nil
	file_proto_replication_proto_depIdxs = nil
}
